import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from matplotlib import pyplot as plt
import random
import numpy as np
import torch
from learning.trainer import Trainer


def plot_per_episode(values, label, color, ylabel, title):
    """Plot a single training metric with the same visual configuration."""
    plt.figure(figsize=(10, 6))
    plt.plot(values, label=label, color=color, linewidth=4, alpha=0.9)
    plt.xlabel("Episode", fontsize=16)
    plt.ylabel(ylabel, fontsize=16)
    plt.title(title, fontsize=16)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

def plot_per_step(values, label, color, ylabel, title):
    """Plot a single training metric with the same visual configuration."""
    plt.figure(figsize=(10, 6))
    plt.plot(values, label=label, color=color, linewidth=4, alpha=0.9)
    plt.xlabel("Step", fontsize=16)
    plt.ylabel(ylabel, fontsize=16)
    plt.title(title, fontsize=16)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# Centralized hyperparameters for both training and evaluation runs.
hyperparams = {
    "discount_factor": 0.99,
    "batch_size": 100,
    "memory_capacity": 10000,
    "max_episodes": 200,
    "goal": 100,
    "network_size": 20,
    "epsilon_max": 1.0,
    "epsilon_min": 0.01,
    "epsilon_decay": 0.0004,
}

# Set True to train from scratch, False to evaluate a saved model.
train_mode = True


if __name__ == "__main__":

    if train_mode:
        # Keep one explicit seed for reproducibility of this run.
        seed = 49
        print(f"Training with seed: {seed}")
        random.seed(seed)
        np.random.seed(seed)
        torch.manual_seed(seed)
        trainer = Trainer(hyperparams, seed)
        rewards, loss, epsilon = trainer.train()

        # Plot all training metrics with the same configuration.
        plot_per_episode(rewards, "reward", "blue", "Reward", "Training Cartpole with RMSProp - Reward")
        plot_per_step(loss, "loss", "orange", "Loss", "Training Cartpole with RMSProp - Loss")
        plot_per_step(epsilon, "epsilon", "green", "Epsilon", "Training Cartpole with RMSProp - Epsilon")

    else:
        # Expects model generated by training mode
        trainer = Trainer(hyperparams, seed=None)
        trainer.test("cartpole_1.pth")